name: 🐛 Bug Report
description: Create a bug
title: "Bug 🍭 "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Bug
      description: Give us more informations about the bug
      placeholder: Bug Description
    validations:
      required: true
